---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-mysql
  labels:
    app: demoapp
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
      component: mysql
  strategy:              # 更新時の動作を指定
    type: Recreate       # 古いPodを停止してから新しいPodを起動
  template:
    metadata:
      labels:
        app: demoapp
        component: mysql
    spec:
      restartPolicy: Always
      volumes:                              #
        - name: data                        # .volumeMountsの.nameで指定
          persistentVolumeClaim:            #
            claimName: demoapp-mysql        # PVCオブジェクトの.metadata.nameを指定
      initContainers:                       # 前処理用のコンテナ
        - name: "remove-lost-found"         # データディレクトリの"lost+found"ディレクトリを削除
          image: "busybox:1.28.4"
          command: 
            - rm
            - -fr
            - /var/lib/mysql/lost+found
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:5.7.22
          livenessProbe:
            tcpSocket:
              port: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
          volumeMounts:                   #
            - name: data                  # .volumesの.nameを指定
              mountPath: /var/lib/mysql   # MySQLのデータディレクトリを指定
          envFrom:
            - configMapRef:
                name: demoapp-mysql-env
            - secretRef:
                name: demoapp-mysql-env
