---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demoapp-redis
  labels:
    app: demoapp
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard

